/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.34.2.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {
  admins: string[];
  [k: string]: unknown;
}
export type ExecuteMsg = ExecMsg;
export type ExecMsg = {
  add_member: {
    admin: string;
    [k: string]: unknown;
  };
} | {
  issue_bounty: {
    donation_denom: string;
    [k: string]: unknown;
  };
} | {
  contribute: {
    amount: Uint128;
    bounty_id: number;
    [k: string]: unknown;
  };
} | {
  issue_and_contribute: {
    amount: Uint128;
    donation_denom: string;
    [k: string]: unknown;
  };
} | {
  accept_fulfillment: {
    amounts: Uint128[];
    bounty_id: number;
    fulfillers: Addr[];
    [k: string]: unknown;
  };
};
export type Uint128 = string;
export type Addr = string;
export type QueryMsg = QueryMsg1;
export type QueryMsg1 = {
  get_admin_list: {
    [k: string]: unknown;
  };
} | {
  get_bounty: {
    bounty_id: number;
    [k: string]: unknown;
  };
};
export interface AdminListResp {
  admins: string[];
  [k: string]: unknown;
}
export interface Bounty {
  balance: Uint128;
  donation_denom: string;
  issuer: Addr;
  paid_out: boolean;
  [k: string]: unknown;
}